<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <parent>
        <groupId>it.mycraft</groupId>
        <artifactId>powerlib</artifactId>
        <version>1.3.7-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>powerlib-commands-bungee</artifactId>

    <repositories>
        <repository>
            <id>bungeecord-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>it.mycraft</groupId>
            <artifactId>powerlib-commands-api</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>it.mycraft</groupId>
            <artifactId>powerlib-bungee</artifactId>
            <version>${project.parent.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.md-5</groupId>
            <artifactId>bungeecord-api</artifactId>
            <version>1.21-R0.4</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
